name: Publish Extension

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          branch: main
          extra_plugins: |
            @semantic-release/git
            @semantic-release/exec
            @semantic-release/changelog

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com

      # - name: Publish to Open VSX Registry
      #   uses: HaaLeo/publish-vscode-extension@v0
      #   with:
      #     pat: ${{ secrets.OPEN_VSX_TOKEN }}
